// This is an auto-generated code file for the model snapshot of the OrdersAPIDbContext class. It contains a 
// partial class definition for the OrdersAPIDbContextModelSnapshot class, which is used to build the model snapshot.

// The BuildModel method in the class is where the model for the database is built using the ModelBuilder class. 
// It defines the properties and their data types for the Order model class. 
// It also specifies the primary key for the Order entity and the name of the table to which it maps.

// The SqlServerModelBuilderExtensions.UseIdentityColumns method is called to configure the model 
// to use SQL Server identity columns for generating unique IDs for the Id column in the Order entity.

// Overall, this code is used to generate a snapshot of the database schema for use in migrations and database updates.







// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdersAPI.Data;

#nullable disable

namespace OrdersAPI.Migrations
{
    [DbContext(typeof(OrdersAPIDbContext))]
    partial class OrdersAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrdersAPI.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
